In [1]:
#Using NumPy create random vector of size 15 having only Integers in the range 1-20.
import numpy as np
n = np.random.randint(1,20,15)
print(n)
#1. Reshape the array to 3 by 5
n1=np.reshape(n,(3,5))
print(n1)
#2. Print array shape.
print(n1.shape)
#3. Replace the max in each row by 0
max_ele = np.amax(n1, axis = 1)
max_ele = max_ele[: , None]
n2 = np.where(n1 == max_ele, 0, n1)
print(n2)

[ 8  9  2  1 17 14 12 16  8  1  8  2  9  4 12]
[[ 8  9  2  1 17]
 [14 12 16  8  1]
 [ 8  2  9  4 12]]
(3, 5)
[[ 8  9  2  1  0]
 [14 12  0  8  1]
 [ 8  2  9  4  0]]
